### ISSUE TITLE
pip install phabricator fails

### ISSUE THREAD

**Issue by gravyflex** [disqus/python-phabricator#44]
pip install phabricator fails with the following error:
{quote}
Traceback (most recent call last):
  File "/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
{quote}

**Comment by thekashifmalik** [comment]
I could not replicate this on **Python 2.7.13** and **Python 3.6.2** on **macOS 10.12.4**.

Closing for now.
